name: buid
on :
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: release - wasm
    runs-on: ubuntu-24.04
    env:
        TZ: Asia/Shanghai
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Setup WASI Environment
        working-directory: .
        run: |
            sudo sh ./.devcontainer/wasi-install.sh
            sudo sh ./.devcontainer/wasm-opt-install.sh
      - name: Setup Environment
        run: |
            sudo apt update
            sudo apt upgrade
            sudo apt install -y llvm clang pkg-config libssl-dev protobuf-compiler

      - name: Update Rust
        run: rustup target add wasm32-wasip1

      - name: Build
        run: |
          export WASI_SYSROOT="/opt/wasi-sdk/wasi-sdk-24.0-x86_64-linux/share/wasi-sysroot/"
          export PATH=$PATH:/opt/binaryen/binaryen-version_119/bin
          cargo build --target wasm32-wasip1 --release

      - name: Build wasm-bindgen
        run: wasm-bindgen target/wasm32-wasip1/release/convert_otf_woff2.wasm --out-dir pkg --target web --no-typescript

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: convert_otf_woff2.wasm