name: build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: release - wasm (WASI)
    runs-on: ubuntu-24.04
    env:
      TZ: Asia/Shanghai
      WASI_VERSION: 24
      WASI_VERSION_FULL: 24.0
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Setup Environment
        run: |
          sudo apt update
          sudo apt install -y llvm clang pkg-config libssl-dev build-essential libc6-dev wget

      - name: Add WASI target
        run: rustup target add wasm32-wasip1

      - name: Download and install WASI SDK
        run: |
          wget https://github.com/WebAssembly/wasi-sdk/releases/download/wasi-sdk-${WASI_VERSION}/wasi-sdk-${WASI_VERSION_FULL}-x86_64-linux.tar.gz
          tar xvf wasi-sdk-${WASI_VERSION_FULL}-x86_64-linux.tar.gz
          echo "WASI_SDK_PATH=${GITHUB_WORKSPACE}/wasi-sdk-${WASI_VERSION_FULL}-x86_64-linux" >> $GITHUB_ENV

      - name: Build for WASI
        run: |
          export CC_wasm32_wasip1="${WASI_SDK_PATH}/bin/clang --sysroot=${WASI_SDK_PATH}/share/wasi-sysroot"
          export CXX_wasm32_wasip1="${WASI_SDK_PATH}/bin/clang++ --sysroot=${WASI_SDK_PATH}/share/wasi-sysroot"
          export AR_wasm32_wasip1="${WASI_SDK_PATH}/bin/llvm-ar"
          export CARGO_TARGET_WASM32_WASIP1_RUSTFLAGS="-L ${WASI_SDK_PATH}/share/wasi-sysroot/lib/wasm32-wasip1 -l c++"
          cargo build --target wasm32-wasip1 --release

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: convert_otf_woff2.wasm
          path: target/wasm32-wasip1/release/convert_otf_woff2.wasm