name: buid
on :
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: release - wasm
    runs-on: ubuntu-24.04
    env:
        TZ: Asia/Shanghai
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Setup Environment
        run: |
            sudo apt update
            sudo apt upgrade
            sudo apt install -y llvm clang pkg-config libssl-dev protobuf-compiler build-essential

      - name: Update Rust
        run: rustup target add wasm32-unknown-unknown

      - name: Install wasm-bindgen
        uses: jetli/wasm-bindgen-action@v0.2.0
        with:
          # Optional version of wasm-bindgen to install(eg. '0.2.83', 'latest')
          version: 'latest'

      - name: Build
        run: cargo build --target wasm32-unknown-unknown --release

      - name: Build wasm-bindgen
        run: wasm-bindgen target/wasm32-unknown-unknown/release/convert_otf_woff2.wasm --out-dir pkg --target web

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: convert_otf_woff2.wasm
          path: pkg/